# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Off by One
tagline:          Programming for the rest of us
url:              https://jwahyoung.github.io/off-by-one
paginate:         5
baseurl:          /
author:
  name:           J.W. Ahyoung
  url:            https://jwahyoung.github.io/off-by-one
  email:          

# Sass
sass:
  sass_dir:          _scss
  style:            :compressed

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/jwahyoung/off-by-one
